import { Bell, CheckCircle, AlertTriangle, XCircle, Filter } from 'lucide-react'
import EmptyState from '../components/EmptyState'

export default function Alerts() {
  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text-primary">Alerts</h1>
          <p className="mt-1 text-[13px] text-text-secondary">
            Security and performance alerts generated by threshold monitoring and vulnerability scanning.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-1.5 rounded-lg border border-border-secondary bg-bg-surface px-3 py-1.5 text-[12px] font-medium text-text-secondary transition hover:text-text-primary">
            <Filter size={13} />
            Filter
          </button>
          <button className="flex items-center gap-1.5 rounded-lg border border-border-secondary bg-bg-surface px-3 py-1.5 text-[12px] font-medium text-text-secondary transition hover:text-text-primary">
            <CheckCircle size={13} />
            Resolve All
          </button>
        </div>
      </div>

      {/* Alert stats */}
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: 'Critical', count: 0, icon: XCircle, color: 'text-severity-critical', bg: 'bg-severity-critical/10 border-severity-critical/20' },
          { label: 'Warning', count: 0, icon: AlertTriangle, color: 'text-severity-high', bg: 'bg-severity-high/10 border-severity-high/20' },
          { label: 'Info', count: 0, icon: Bell, color: 'text-chart-blue', bg: 'bg-chart-blue/10 border-chart-blue/20' },
          { label: 'Resolved', count: 0, icon: CheckCircle, color: 'text-accent-primary', bg: 'bg-accent-primary/10 border-accent-primary/20' },
        ].map((stat) => (
          <div key={stat.label} className={`rounded-xl border p-4 ${stat.bg}`}>
            <div className="flex items-center justify-between">
              <p className={`text-[11px] font-semibold uppercase tracking-wider ${stat.color}`}>{stat.label}</p>
              <stat.icon size={16} className={stat.color} />
            </div>
            <p className={`text-3xl font-bold mt-2 ${stat.color}`}>{stat.count}</p>
          </div>
        ))}
      </div>

      {/* Alert list */}
      <div className="rounded-xl border border-border-primary bg-bg-surface overflow-hidden">
        <div className="grid grid-cols-[80px_1fr_1fr_120px_100px] gap-3 items-center px-5 py-3 text-[10px] font-semibold uppercase tracking-wider text-text-muted border-b border-border-primary">
          <span>Severity</span>
          <span>Alert</span>
          <span>Resource</span>
          <span>Time</span>
          <span>Status</span>
        </div>

        <EmptyState
          icon={Bell}
          title="No alerts"
          message="Alert monitoring will be active after metrics collection (Phase 8) and security scanning (Phase 11) are configured."
        />

        <div className="border-t border-border-primary px-5 py-2.5 text-[11px] text-text-muted">
          Showing 0 alerts
        </div>
      </div>
    </div>
  )
}
